apiVersion: v1
kind: Service
metadata:
  name: goapp
  annotations:
    serviceloadbalancer/lb.algorithm: "roundrobin"  
  labels:
    app: goapp
spec:
  ports:
  - port: 80
    targetPort: 8484
  selector:
    name: goapp
  sessionAffinity:
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: goapp
  labels:
    app: goapp
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: goapp
        app: goapp
    spec:
      containers:
        - name: goapp
          image: jangaraj/go-app:v1
          ports:
          - containerPort: 8484
      nodeSelector:
        role: webserver
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: service-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer
        version: v1
    spec:
      nodeSelector:
        role: loadbalancer
      containers:
      - image: monitoringartist/servicelb:0.7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 1936
          protocol: TCP
        resources: {}