sudo: required

services:
  - docker
  
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- export REPO=jangaraj/go-app
- docker build --rm=true -t $REPO:binary -f devops/Dockerfile . 
- docker run --rm=true -ti -v $PWD:/tmp $REPO:binary cp /main /tmp
- docker build --rm=true -t $REPO:$TRAVIS_BUILD_NUMBER .
- docker push $REPO:$TRAVIS_BUILD_NUMBER
